mcc: '999'
mnc: '70'
nci: '0x000000010'
idLength: 32
tac: 1
linkIp: 10.10.0.20
ngapIp: 10.10.0.20
gtpIp: 10.10.0.20

amfConfigs:
  - address: 10.10.0.11
    port: 38412

slices:
  - sst: 1

ignoreStreamIds: true
