logger:
  level: info

global:
  max:
    ue: 1024

sbi:
  server:
    no_tls: true
  client:
    no_tls: true

bsf:
  sbi:
    - addr: 10.10.0.18
      port: 7777

nrf:
  sbi:
    - addr: 10.10.0.10
      port: 7777
